### ISSUE TITLE
need patches: nc, wget, dig, host?

### ISSUE THREAD

**Issue by xlz** [libos-nuse/net-next-nuse#30]
I saw the slides [Userspace networking: Network Stack in Userspace](http://www.slideshare.net/hajimetazaki/nuse-network-stack-in-userspace-at-osio) which say ping and iperf work but nc, wget, dig, and host do not work.

Why do they not work, where is the technical reason? Is it because of unimplemented syscalls they require?

Also, congratulations, your code works on my Debian 8.0. I can ping google.com.

**Comment by thehajime** [comment]
This issue was moved to libos-nuse/linux-libos-tools#9
