### ISSUE TITLE
This could be the road to freestanding protocol-less all-software networking

### ISSUE THREAD

**Issue by yitzhakbg** [libos-nuse/net-next-nuse#41]
Being as the project is in its initial stages, most of the talk is (necessarily) technical. In my view this project could be the road to the Holy Grail of protocol-free Purely Software Networking. See [Tearing Down the Protocol Wall](https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile) on my LinkedIn page.
I have some ideas and proposals which are burning my insides. Where can we discuss them?

**Comment by thehajime** [comment]
I've been thinking to create communication channel for libos/nuse. So far dedicate channel is only gitter chat, which is on top page (README.md) and almost no one is there, or this issue tracker. 

I will setup mailing lists for these kind of discussion.

**Comment by yitzhakbg** [comment]
Thanks

**Comment by thehajime** [comment]
I've created a mailing list for the general discussion about LibOS and NUSE.

https://groups.google.com/forum/#!forum/libos-nuse
